name: Sync IP addresses

on:
  pull_request:
    paths:
      - 'list.json'

jobs:
  update-ip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dnsutils
        run: sudo apt-get install dnsutils

      - name: Update IP addresses
        run: |
          #!/bin/bash

          # Read JSON file
          JSON_FILE="list.json"
          JSON_CONTENT=$(cat $JSON_FILE)

          # Loop through hosts
          HOSTS=$(echo $JSON_CONTENT | jq -c '.swarms | .. | .host?' | grep -v null | sed 's/\"//g')
          for HOST in $HOSTS; do
            # Get IP address
            IP=$(dig +short $HOST)
            if [ -n "$IP" ]; then
              # Update or add "ip" property
              JSON_CONTENT=$(echo $JSON_CONTENT | jq --arg host "$HOST" --arg ip "$IP" '.swarms[] | select(.list[]?.host == $host) |= .list[] |= . + {"ip": $ip}')
            fi
          done

          # Write updated JSON back to file
          echo $JSON_CONTENT > $JSON_FILE

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add list.json
          git commit -m "Update IP addresses"
          git push
